# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - EdGraph/v2.0/instance
  paths:
    exclude:
    - azure-pipelines-azure-functions.yml
    - DataImport.AzureFunctions/*
    - DataImport.AzureFunctions.Manager/*

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

stages:
- stage: DockerBuild
  jobs:
  - job:
    steps:
      - task: Docker@2
        displayName: Login to ACR
        inputs:
          command: login
          containerRegistry: 'ewcontainerscus'
      - task: Docker@2
        displayName: Login to ACR
        inputs:
          command: login
          containerRegistry: 'eginfracrqausc'
      - task: Docker@2
        displayName: Login to ACR
        inputs:
          command: login
          containerRegistry: 'eginfracrproductionusc'
      - task: Docker@2
        displayName: Login to ACR
        inputs:
          command: login
          containerRegistry: 'eginfracrdevelopmentusc'
      - task: Docker@2
        inputs:
          repository: 'edfi/dataimport-web'
          command: 'buildAndPush'
          Dockerfile: '$(Build.SourcesDirectory)/DataImport.Web/Dockerfile'
          buildContext: '$(Build.SourcesDirectory)'
          tags: |
            alpine-sql-v2.0.0-instance.$(Build.BuildNumber)
            alpine-sql-v2.0.0-instance.latest
      - task: Docker@2
        displayName: Logout of ACR
        inputs:
          command: logout
          containerRegistry: eginfracrproductionusc
      - task: Docker@2
        displayName: Logout of ACR
        inputs:
          command: logout
          containerRegistry: eginfracrdevelopmentusc
      - task: Docker@2
        displayName: Logout of ACR
        inputs:
          command: logout
          containerRegistry: eginfracrqausc
      - task: Docker@2
        displayName: Logout of ACR
        inputs:
          command: logout
          containerRegistry: ewcontainerscus
