# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - EdGraph/v2.0/instance
  paths:
    include:
    - azure-pipelines-azure-functions.yml
    - DataImport.AzureFunctions/*
    - DataImport.AzureFunctions.Manager/*
    exclude:
    - azure-pipelines.yml
    - '*'

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

stages:
- stage: DockerBuild
  jobs:
  - job:
    steps:
      - task: Docker@2
        displayName: Login to ACR
        inputs:
          command: login
          containerRegistry: 'ewcontainerscus'
      - task: Docker@2
        inputs:
          containerRegistry: 'ewcontainerscus'
          repository: 'edfi/dataimport-web/azure-functions'
          command: 'buildAndPush'
          Dockerfile: '$(Build.SourcesDirectory)/DataImport.AzureFunctions/Dockerfile'
          buildContext: '$(Build.SourcesDirectory)'
          tags: |
            bullseye-slim-azurefunctions-v1.$(Build.BuildNumber)
            bullseye-slim-azurefunctions.latest
      - task: Docker@2
        inputs:
          containerRegistry: 'ewcontainerscus'
          repository: 'edfi/dataimport-web/azure-functions-manager'
          command: 'buildAndPush'
          Dockerfile: '$(Build.SourcesDirectory)/DataImport.AzureFunctions.Manager/Dockerfile'
          buildContext: '$(Build.SourcesDirectory)'
          tags: |
            bullseye-slim-azurefunctions-manager-v1.$(Build.BuildNumber)
            bullseye-slim-azurefunctions-manager.latest
      - task: Docker@2
        displayName: Logout of ACR
        inputs:
          command: logout
          containerRegistry: ewcontainerscus
